import { useRef } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import useDrawer from '../../hooks/useDrawer';
import { PRIORITY_META, TYPE_META } from './data';

const EASE = [.16, 1, .3, 1];

export default function NotificationDrawer({ notification, onToggleRead, onArchive, onClose }) {
  // Escape, scroll lock, focus trap and focus restore — shared by every drawer.
  const panelRef = useRef(null);
  useDrawer(Boolean(notification), onClose, panelRef);

  const type = notification ? TYPE_META[notification.type] : null;
  const priority = notification ? PRIORITY_META[notification.priority] : null;

  const rows = notification ? [
    { label: 'Context', value: notification.context, icon: 'bi-diagram-3' },
    { label: 'Why it matters', value: notification.impact, icon: 'bi-graph-up-arrow' },
    { label: 'Suggested action', value: notification.action, icon: 'bi-signpost-split' },
  ] : [];

  return (
    <AnimatePresence>
      {notification && (
        <>
          <motion.div
            className="nt-drawer-backdrop"
            initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
            transition={{ duration: .28 }} onClick={onClose} aria-hidden="true"
          />
          <motion.aside
            ref={panelRef}
            className="nt-drawer"
            role="dialog" aria-modal="true" aria-label={notification.title}
            initial={{ x: '100%' }} animate={{ x: 0 }} exit={{ x: '100%' }}
            transition={{ duration: .42, ease: EASE }}
          >
            <header className="nt-drawer-head">
              <span className={`nt-drawer-icon tone-${type.tone}`}><i className={`bi ${type.icon}`} aria-hidden="true" /></span>
              <div>
                <span className="nt-drawer-tags">
                  <span className={`nt-priority tone-${priority.tone}`}>{priority.label}</span>
                  <span className="nt-type">{type.label}</span>
                </span>
                <h3>{notification.title}</h3>
                <p>{notification.time} · {notification.meta}</p>
              </div>
              <button type="button" className="nt-drawer-close" onClick={onClose} aria-label="Close notification">
                <i className="bi bi-x-lg" aria-hidden="true" />
              </button>
            </header>

            <div className="nt-drawer-body">
              <p className="nt-drawer-detail">{notification.detail}</p>

              {rows.map((row, index) => (
                <motion.section
                  key={row.label}
                  className="nt-drawer-block"
                  initial={{ opacity: 0, y: 14 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: .48, delay: .24 + index * .1, ease: EASE }}
                >
                  <h4><i className={`bi ${row.icon}`} aria-hidden="true" />{row.label}</h4>
                  <p>{row.value}</p>
                </motion.section>
              ))}

              <p className="nt-drawer-note">
                <i className="bi bi-info-circle" aria-hidden="true" />
                Placeholder notification — nothing here was generated by a live system.
              </p>
            </div>

            <footer className="nt-drawer-foot">
              <button type="button" className="nt-btn nt-btn-primary" onClick={() => { onToggleRead(notification.id); onClose(); }}>
                <i className={`bi bi-${notification.read ? 'envelope' : 'envelope-open'}`} aria-hidden="true" />
                Mark as {notification.read ? 'unread' : 'read'}
              </button>
              <button type="button" className="nt-btn nt-btn-ghost" onClick={() => { onArchive(notification.id); onClose(); }}>
                <i className={`bi bi-${notification.archived ? 'arrow-counterclockwise' : 'archive'}`} aria-hidden="true" />
                {notification.archived ? 'Restore' : 'Archive'}
              </button>
            </footer>
          </motion.aside>
        </>
      )}
    </AnimatePresence>
  );
}
