# Generated by Django 6.0.7 on 2026-08-05 02:19

import authentication.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', authentication.managers.UserManager()),
            ],
        ),
    ]
