# Generated by Django 6.0.7 on 2026-08-04 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=100)),
                ('sale_date', models.DateField(db_index=True)),
                ('quantity_sold', models.PositiveIntegerField(default=0)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='products.product')),
            ],
            options={
                'ordering': ['-sale_date'],
                'indexes': [models.Index(fields=['product', 'sale_date'], name='sales_sales_product_c6b391_idx'), models.Index(fields=['invoice_number'], name='sales_sales_invoice_7d9c6d_idx')],
            },
        ),
    ]
